# fly.toml app configuration file generated for part13-bloglist-app on 2025-03-06T09:04:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part13-bloglist-app'
primary_region = 'otp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
