# fly.toml app configuration file generated for bloglist-delicate-waterfall-9086 on 2024-11-28T09:34:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloglist-delicate-waterfall-9086'
primary_region = 'otp'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node index.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
