name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Change directory to part11/full-stack-open-pokedex-main
        run: cd part11/full-stack-open-pokedex-main
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
