name: 🚀 deployment pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'part11/**'
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths:
      - 'part11/**'

jobs:
  build_test_lint:
    name: build, test and lint the code
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: part11/full-stack-open-pokedex-main

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependencies
        run: npm install

      - name: check style
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: install playwright browsers
        run: npx playwright install --with-deps

      - name: run playwright tests
        run: npx playwright test

      - name: print github context and commits
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          GITHUB_PULL_REQUEST_MERGED: ${{ github.event.pull_request.merged }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_COMMITS: ${{ toJson(github.event.commits) }}
          GITHUB_COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: |
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Event action: $GITHUB_EVENT_ACTION"
          echo "Pull request merged: $GITHUB_PULL_REQUEST_MERGED"
          echo "Ref: $GITHUB_REF"
          echo "Commits: $GITHUB_COMMITS"
          echo "Commit Messages: $GITHUB_COMMIT_MESSAGES"

  deploy:
    name: deploy to fly.io
    needs: build_test_lint
    if: >
      ${{ github.event_name == 'push' &&  !contains(join(github.event.commits.*.message, '
      '),'#skip') }}

    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: part11/full-stack-open-pokedex-main

    steps:
      - uses: actions/checkout@v4

      - name: setup fly.io cli
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: deploy to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    name: tag and release the code
    needs: deploy
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
