name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd part11/full-stack-open-pokedex-main
          npm install
      - name: Check style
        run: |
          cd part11/full-stack-open-pokedex-main
          npm run eslint
      - name: Build
        run: |
          cd part11/full-stack-open-pokedex-main
          npm run build
      - name: Test
        run: |
          cd part11/full-stack-open-pokedex-main
          npm run test
      - name: Install Playwright Browsers
        run: |
          cd part11/full-stack-open-pokedex-main
          npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          cd part11/full-stack-open-pokedex-main
          npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
